# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='contents',
            field=models.TextField(help_text='Separate each menu items by comma'),
        ),
        migrations.AlterField(
            model_name='item',
            name='excludes',
            field=models.TextField(blank=True, help_text='Separate each menu items by comma', null=True),
        ),
    ]
