# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 08:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurantlocation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 11, 8, 14, 55, 105584, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
