# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 13:14
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_restaurantlocation_owner'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='restaurantlocation',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
