# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_auto_20170925_1314'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='restaurantlocation',
            managers=[
            ],
        ),
    ]
